version: '3.2'

services:
  api:
    container_name: APP_backend_Test
    restart: always
    build: .
    ports:
      - '3000:3000/tcp'
    links:
      - db:db
    volumes:
      - .:/usr/src/app
    depends_on:
      db:
        condition: service_healthy
  db:
    image: mysql
    container_name: DB_backend_Test
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - '3306:3306'
    expose:
      - 3306
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_USER: user
      MYSQL_PASSWORD: pass
      MYSQL_DATABASE: test
      MYSQL_TCP_PORT: 3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      timeout: 20s
      retries: 10
